services:
  - type: web
    name: grocerygetter-server
    env: docker
    rootDir: server
    dockerfilePath: Dockerfile
    envVars:
      - key: DefaultConnection
        value: "Host=postgresql;Database=grocerygetterdb;Username=production;Password=fW61hU6JlnTSCLY8vZp7wmLwUPpiyabz"
      - key: PostgreSqlConnection
        value: "Host=postgresql;Database=grocerygetterdb;Username=production;Password=fW61hU6JlnTSCLY8vZp7wmLwUPpiyabz"