-- Insert data into the Store table
INSERT INTO "Store" ("Name", "Address", "City", "State", "ZipCode", "PhoneNumber")
VALUES
    ('Alphabetical', 'NA', 'NA', 'NA', 'NA', 'NA'),
    ('Festival Foods', '1001 Main Avenue', 'De Pere', 'WI', '54115', '9203366520');

-- Get Store ID
DO $$ 
DECLARE store_id INT;
BEGIN
    -- Insert data into the Layout table
    SELECT "Id" INTO store_id FROM "Store" WHERE "Name"='Alphabetical';
    INSERT INTO "Layout" ("StoreId", "Name")
    VALUES (store_id, 'Alphabetical-A-Z');

    SELECT "Id" INTO store_id FROM "Store" WHERE "Name"='Festival Foods';
    INSERT INTO "Layout" ("StoreId", "Name")
    VALUES (store_id, 'Festival Foods-De Pere');
END $$;

-- Insert data into the Aisle table
DO $$ 
DECLARE layout_id INT;
BEGIN
    SELECT "Id" INTO layout_id FROM "Layout" WHERE "Name"='Alphabetical-A-Z';
    INSERT INTO "Aisle" ("LayoutId", "Name", "Lineup") 
    VALUES
        (layout_id, 'Alphabetical', 1),
        (layout_id, 'InCart', 9998);

    SELECT "Id" INTO layout_id FROM "Layout" WHERE "Name"='Festival Foods-De Pere';
    INSERT INTO "Aisle" ("LayoutId", "Name", "Lineup") 
    VALUES
        (layout_id, '1', 4),
        (layout_id, '2', 5),
        (layout_id, '3', 6),
        (layout_id, '4', 7),
        (layout_id, '5', 8),
        (layout_id, '6', 9),
        (layout_id, '7', 10),
        (layout_id, '8', 11),
        (layout_id, '9', 12),
        (layout_id, '10', 22),
        (layout_id, '11', 21),
        (layout_id, '12', 20),
        (layout_id, '13', 19),
        (layout_id, '14', 18),
        (layout_id, 'Front End', 23),
        (layout_id, 'Meat', 13),
        (layout_id, 'Bakery', 17),
        (layout_id, 'Natural', 9997),
        (layout_id, 'Dairy', 14),
        (layout_id, 'Produce', 1),
        (layout_id, 'Frozen', 16),
        (layout_id, 'Wine & Spirits', 15),
        (layout_id, 'Deli', 3),
        (layout_id, 'InCart', 9998),
        (layout_id, 'Unassigned', 9999);
END $$;

-- Insert data into the Product table
INSERT INTO "Product" ("Name")
VALUES
    ('After Shave'),
    ('Air Fresheners'),
    ('Aluminum Foil'),
    ('Ammonia'),
    ('Apple Juice'),
    ('Asian Foods'),
    ('Applesauce'),
    ('Aspirin'),
    ('Automotive'),
    ('Baby Formula'),
    ('Baby Needs'),
    ('Bacon Bits'),
    ('Baked Beans'),
    ('Bakeware'),
    ('Baking Chocolate'),
    ('Baking Soda'),
    ('Band-Aids'),
    ('Barbecue Sauce'),
    ('Barley'),
    ('Bar Soap'),
    ('Bath Tissue'),
    ('Batteries'),
    ('Beans (Dried)'),
    ('Beef'),
    ('Beef Stick (Snacks)'),
    ('Beer'),
    ('Bird Seed'),
    ('Bisquick'),
    ('Bleach'),
    ('Body Wash'),
    ('Books'),
    ('Boxed Dinners'),
    ('Bread (Bakery Fresh)'),
    ('Bread (Commercial)'),
    ('Bread Crumbs'),
    ('Bread (Frozen)'),
    ('Bread Sticks'),
    ('Brooms'),
    ('Bulk Spice'),
    ('Cake'),
    ('Cake Mixes'),
    ('Candles'),
    ('Candied Fruit'),
    ('Candles (Birthday)'),
    ('Candy Bags'),
    ('Candy Single Bars'),
    ('Canning Supplies'),
    ('Capers'),
    ('Carrots'),
    ('Cat Food'),
    ('Cat Litter'),
    ('Cereal (Hot/Cold)'),
    ('Charcoal/Logs'),
    ('Cheese'),
    ('Cheese (Shredded)'),
    ('Cheesecloth'),
    ('Chicken'),
    ('Chili (Canned)'),
    ('Chili Sauce (Sriracha)'),
    ('Chutney'),
    ('Cigarettes'),
    ('Cleaners'),
    ('Cling Wrap'),
    ('Clothes Line'),
    ('Club Soda'),
    ('Cocktail Sauce'),
    ('Coconut Oil'),
    ('Coconut'),
    ('Cocoa (Baking)'),
    ('Coffee'),
    ('Coffee Creamer'),
    ('Coffee Filters'),
    ('Condensed Milk'),
    ('Cookies'),
    ('Cooking Bags'),
    ('Cooking Wines'),
    ('Cornstarch'),
    ('Cotton Balls'),
    ('Crabmeat (Canned)'),
    ('Crackers'),
    ('Cranberry Juice'),
    ('Cranberry Sauce'),
    ('Croutons'),
    ('Cupcake Liners'),
    ('Dates'),
    ('Deodorant'),
    ('Diapers'),
    ('Diabetic & Diet Needs'),
    ('Dinner Napkins'),
    ('Dish Detergent'),
    ('Distilled Water'),
    ('Dog Food/Treats'),
    ('Donuts'),
    ('Dry Seasoning Packets'),
    ('Drink Enhancers (flavoring)'),
    ('Eggs'),
    ('Electrical Needs'),
    ('Energy Bars'),
    ('Energy Drinks'),
    ('Envelopes'),
    ('Evaporated Milk'),
    ('Fabric Softener'),
    ('Facial Tissues'),
    ('Firewood Bundle'),
    ('Fish (Canned)'),
    ('Floor Cleaner'),
    ('Flour'),
    ('Foil Baking Pans'),
    ('Freezer Paper'),
    ('French Fried Onions'),
    ('Frosting'),
    ('Fruit (Canned)'),
    ('Fruit (Dried)'),
    ('Fruit Snacks'),
    ('Furniture Polish'),
    ('Garbage Bags'),
    ('Garlic (Minced)'),
    ('Gatorade'),
    ('Gelatin'),
    ('Glass Cleaner'),
    ('Gloves'),
    ('Granola Bars'),
    ('Gravy'),
    ('Greeting Cards'),
    ('Grits'),
    ('Hamburger Buns'),
    ('Hand Lotion'),
    ('Handi Wipes'),
    ('Handi-Wrap'),
    ('Hardware'),
    ('Hispanic Foods'),
    ('Honey'),
    ('Horseradish Sauce'),
    ('Hosiery'),
    ('Hot Cocoa'),
    ('Hotdog Buns'),
    ('Housewares'),
    ('Household Cleaners'),
    ('Ice Cream Cones'),
    ('Ice Cream Toppings'),
    ('Iced Tea'),
    ('Instant Potatoes'),
    ('Insecticides'),
    ('Jam/Jelly'),
    ('Jell-O (Cups)'),
    ('Jell-O (Box)'),
    ('Juice'),
    ('Ketchup'),
    ('Kidney Beans'),
    ('Kitchen Gadgets'),
    ('Kleenex'),
    ('Kool Aid'),
    ('Lasagna Noodles (Dry)'),
    ('Laundry Detergent'),
    ('Laxatives'),
    ('Lemonade (Frozen)'),
    ('Lemon Juice'),
    ('Light Bulbs'),
    ('Lima Beans'),
    ('Liquor'),
    ('Lunch Bags'),
    ('Lunch Meat'),
    ('Magazines'),
    ('Manwich'),
    ('Maraschino Cherries'),
    ('Marinades (Liquid)'),
    ('Marshmallows'),
    ('Matches'),
    ('Mayonnaise'),
    ('Meat (Canned)'),
    ('Milk'),
    ('Milk (Powdered)'),
    ('Miracle Whip'),
    ('Molasses'),
    ('Mops'),
    ('Moth Balls'),
    ('Nail Care'),
    ('Napkins (Paper)'),
    ('Noodles'),
    ('Nutella'),
    ('Nuts (Baking)'),
    ('Nuts (Snacks)'),
    ('Oatmeal'),
    ('Oil (Cooking)'),
    ('Olives'),
    ('Oven Cleaner'),
    ('Oysters (Canned)'),
    ('Pancake Mix'),
    ('Pancake Syrup'),
    ('Paper Cups'),
    ('Paper Plates'),
    ('Paper Towels'),
    ('Pasta (Dried)'),
    ('Pasta Sauce'),
    ('Pasta (Refrigerated Premade)'),
    ('Peanut Butter'),
    ('Pesto'),
    ('Pet Supplies'),
    ('Pepper'),
    ('Pickles'),
    ('Pie Crust'),
    ('Pie Filling'),
    ('Pimientos'),
    ('Pine Nuts'),
    ('Pinto Beans'),
    ('Pita Chips'),
    ('Pizza Crust (Boxed)'),
    ('Pizza Mix'),
    ('Pizza Sauce'),
    ('Plastic Flatware'),
    ('Plastic Wrap'),
    ('Popcorn (Bagged)'),
    ('Popcorn (Microwave)'),
    ('Pop Tarts'),
    ('Potato Chips'),
    ('Potatos'),
    ('Potatoes (Dry)'),
    ('Protein Bars'),
    ('Prunes'),
    ('Pudding'),
    ('Pumpkin (Canned)'),
    ('Raisins'),
    ('Ramen Noodles'),
    ('Rawhide'),
    ('Relish'),
    ('Rice'),
    ('Rice-A-Roni'),
    ('Rice Cakes'),
    ('Rubber Gloves'),
    ('Rug Doctor Rental'),
    ('Salad Dressing'),
    ('Salsa'),
    ('Salt (Table/Sea)'),
    ('Salt (Sidewalk)'),
    ('Salt (Water Softener)'),
    ('Sandwich Bags'),
    ('SauerKraut (Bag)'),
    ('Sauerkraut (Canned)'),
    ('School Supplies'),
    ('Seltzer Water'),
    ('Shampoo'),
    ('Shoe Laces'),
    ('Shortening'),
    ('Shrimp (Canned)'),
    ('Skin Care'),
    ('Slim Fast'),
    ('Snacks'),
    ('Soda'),
    ('Soup'),
    ('Soy Sauce'),
    ('Spaghetti'),
    ('Spam'),
    ('Spices'),
    ('Sponges'),
    ('Sports Drinks'),
    ('Stain Remover'),
    ('Starch (Spray)'),
    ('Steak Sauce'),
    ('Stew (Canned)'),
    ('Storage Bags'),
    ('Straws'),
    ('Stuffing'),
    ('Sugar'),
    ('Sure Jell'),
    ('Super Glue'),
    ('Tabasco Sauce'),
    ('Taco Shells'),
    ('Tahini'),
    ('Tang'),
    ('Tartar Sauce'),
    ('Tea (Packets/Bags)'),
    ('Tea (Bottles & Jugs)'),
    ('Toilet Paper'),
    ('Tomato Paste'),
    ('Tomato Sauce'),
    ('Tonic Water'),
    ('Toothpaste'),
    ('Tortilla Chips'),
    ('Tuna'),
    ('Vegetables (Canned)'),
    ('Vegetable Oil'),
    ('Velveeta'),
    ('Vinegar'),
    ('Vitamins'),
    ('Water Chestnuts'),
    ('Water (Distilled)'),
    ('Water (Drinking)'),
    ('Water Refill'),
    ('Wax Paper'),
    ('Windex'),
    ('Wine'),
    ('Worcestershire Sauce'),
    ('Yams (Canned)'),
    ('Yeast (Dry)'),
    ('Yeast Cakes');